name: Dotnet Build

env:
  CAST_TOKEN : ${{ secrets.CAST_TOKEN }}
  CAST_LOGIN : ${{ secrets.CAST_LOGIN }}
  CAST_PASSWORD : ${{ secrets.CAST_PASSWORD }}
  CAST_API_URL : ${{ secrets.CAST_API_URL }}
  CAST_DOMAIN_ID : ${{ secrets.CAST_DOMAIN_ID }}

on:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Perform security code scan
      uses: security-code-scan/security-code-scan-add-action@v1.2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.1.x
          6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Unit Test
      run: dotnet test Cast.RestClient.Tests --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Integration Test
      run: dotnet test Cast.RestClient.Integration.Tests --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      
    - name: Publish coverage reports to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        fail_ci_if_error: true
        verbose: true
    
    - name: Convert SCS sarif for uploading to GitHub
      uses: security-code-scan/security-code-scan-results-action@v1.3
        
    - name: Upload sarif	
      uses: github/codeql-action/upload-sarif@v1