name: Pull Request Verification

env:
  CAST_TOKEN : ${{ secrets.CAST_TOKEN }}
  CAST_LOGIN : ${{ secrets.CAST_LOGIN }}
  CAST_PASSWORD : ${{ secrets.CAST_PASSWORD }}
  CAST_API_URL : ${{ secrets.CAST_API_URL }}
  CAST_DOMAIN_ID : ${{ secrets.CAST_DOMAIN_ID }}

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit tests with coverage report
      run: dotnet test Cast.RestClient.Tests --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Integration tests with coverage report
      run: dotnet test Cast.RestClient.Integration.Tests --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Run Codecov without publishing reports
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        fail_ci_if_error: false
        verbose: true
        dry_run: true