name: Pull Request Verification

env:
  CAST_TOKEN : ${{ secrets.CAST_TOKEN }}
  CAST_LOGIN : ${{ secrets.CAST_LOGIN }}
  CAST_PASSWORD : ${{ secrets.CAST_PASSWORD }}
  CAST_API_URL : ${{ secrets.CAST_API_URL }}
  CAST_DOMAIN_ID : ${{ secrets.CAST_DOMAIN_ID }}

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.*

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Unit tests with cobertura coverage report
      run: dotnet test Cast.RestClient.Tests --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory coverage
    
    - name: Copy coverage report to predictable location
      run: cp coverage/**/coverage.cobertura.xml coverage/coverage.cobertura.xml
      
    - name: Generate code coverage summary report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: ./coverage/coverage.cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add coverage report into PR comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
